name: Test

on:
  workflow_call:
  workflow_run:
    workflows: ["ğŸ— Build"]
jobs:
  test_ubuntu:
    strategy:
      matrix:
        version: [20.04, 22.04]
    runs-on: ubuntu-${{ matrix.version}}
    steps:
      - uses: legleux/failure/.github/actions/ubuntu/test@main
      - uses: actions/download-artifact@master
        with:
          name: executable
          path: ${{github.workspace}}

          # path: executable
      - run: cat executable
